inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1

Bundler/DuplicatedGem:
  Enabled: false

Naming/FileName:
  Exclude:
    - bundler-multilock.gemspec
    - lib/bundler-multilock.rb

Style/Documentation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
