name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7, "3.0", 3.1, 3.2]
        bundler-version: [2.4.19, 2.4.22, 2.5.2]
        exclude:
          - ruby-version: 2.7
            bundler-version: 2.5.2
    env:
      BUNDLER_VERSION: ${{ matrix.bundler-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: ${{ matrix.bundler-version }}
          bundler-cache: true
      - name: Run tests
        run: bin/rspec

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: Run RuboCop
        run: bin/rubocop
        timeout-minutes: 2
