name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.6, 2.7, "3.0", 3.1, 3.2]
        bundler-version: [2.4.19, 2.4.22, 2.5.7]
        exclude:
          - ruby-version: 2.6
            bundler-version: 2.5.7
          - ruby-version: 2.7
            bundler-version: 2.5.7
    env:
      BUNDLER_VERSION: ${{ matrix.bundler-version }}
      BUNDLE_LOCKFILE: active
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: latest
          bundler: ${{ matrix.bundler-version }}
          bundler-cache: true
      - name: Run tests
        run: bin/rspec

  lint:
    runs-on: ubuntu-latest

    env:
      BUNDLE_LOCKFILE: active
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
          rubygems: latest
      - name: Run RuboCop
        run: bin/rubocop
        timeout-minutes: 2
