name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: [3.1, 3.2, 3.3, 3.4]
        bundler-version: [2.4.19, 2.4.22, 2.5.10, 2.6.4]
    env:
      BUNDLER_VERSION: ${{ matrix.bundler-version }}
      BUNDLE_LOCKFILE: active
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: latest
          bundler: ${{ matrix.bundler-version }}
          bundler-cache: true
      - name: Run tests
        run: bin/rspec

  lint:
    runs-on: ubuntu-latest

    env:
      BUNDLE_LOCKFILE: active
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
          rubygems: latest
      - name: Run RuboCop
        run: bin/rubocop
        timeout-minutes: 2
